{
 "title": "OpenSearch Example eCommerce Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Sample eCommerce Orders",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Instructions\n\n- Run `npm run server` to start Grafana and an OpenSearch cluster\n- Navigate to [Add sample data](http://localhost:5601/app/home#/tutorial_directory)\n- Under `Sample eCommerce orders` click \"Add data\"\n\n**NOTE**: The docker-compose file mounts a volume to persist OpenSearch data. When sample data is added, it is only added up to the point in time when you added the data, i.e. no new data gets added after you add the sample data. If there are no results, you can either extend the time range or delete the `opensearch-data1` and `opensearch-data2` volumes and re-add the sample data following the instructions above."
   }
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "order_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "taxful_total_price", "id": "1", "type": "sum" }
     ],
     "timeField": "order_date"
    }
   ]
  },
  {
   "title": "Sales by Category",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "category.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "order_date", "id": "2", "settings": { "interval": "3h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_quantity", "id": "1", "type": "sum" }
     ],
     "timeField": "order_date"
    }
   ]
  },
  {
   "title": "Transactions Per Day",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "order_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "order_date"
    }
   ]
  },
  {
   "title": "Average Spend Per Order",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "order_id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "taxful_total_price", "id": "1", "type": "avg" }
     ],
     "timeField": "order_date"
    }
   ]
  },
  {
   "title": "Promotion Tracking",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Revenue Trousers",
     "bucketAggs": [
      { "field": "order_date", "id": "2", "settings": { "interval": "12h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "taxful_total_price", "id": "1", "type": "sum" }
     ],
     "query": "products.product_name:*trouser*",
     "timeField": "order_date"
    },
    {
     "alias": "Revenue Watches",
     "bucketAggs": [
      { "field": "order_date", "id": "2", "settings": { "interval": "12h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "taxful_total_price", "id": "1", "type": "sum" }
     ],
     "query": "products.product_name:*watch*",
     "timeField": "order_date"
    },
    {
     "alias": "Revenue Bags",
     "bucketAggs": [
      { "field": "order_date", "id": "2", "settings": { "interval": "12h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "taxful_total_price", "id": "1", "type": "sum" }
     ],
     "query": "products.product_name:*bag*",
     "timeField": "order_date"
    },
    {
     "alias": "Revenue Cocktail Dresses",
     "bucketAggs": [
      { "field": "order_date", "id": "2", "settings": { "interval": "12h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "taxful_total_price", "id": "1", "type": "sum" }
     ],
     "query": "products.product_name:*cocktail dress*",
     "timeField": "order_date"
    }
   ]
  }
 ]
}