name: Compatibility check
on: [push, pull_request]
permissions:
  contents: read
jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build
      - name: Build plugin
        run: yarn build
      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@8c65927553042c5cf701877636dd37344a8a0ce1 # v1
        with:
          module: './src/module.ts'
          comment-pr: 'no'
          fail-if-incompatible: 'yes'
          targets: '@grafana/data,@grafana/ui,@grafana/runtime,@grafana/e2e-selectors'
