name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@2b6533cf7a036b781cd1e4817823743b1fdad089 # ci-cd-workflows/v8.0.1
    permissions:
      contents: read
      id-token: write
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
